import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
size = 22
[window]

opacity = 0.9
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
