alias be='bundle exec'
alias bi='bundle install'
alias bw='bin/webpack-dev-server'
alias rails-install-and-migrate='ggpull && bundle install && yarn install && bin/rails db:migrate'
alias rails-checkout-schema-changes='gco **/*schema.rb'
alias rails-setup='rails-install-and-migrate && rails-checkout-schema-changes'
alias rc='rails console'
alias add-solargraph-config='cp ~/.config/solargraph/.solargraph.yml ./'
alias vi='nvim'
alias rails-credentials='EDITOR="nvim" rails credentials:edit'
alias rails-credentials-dev='EDITOR="nvim" rails credentials:edit --environment development'
alias rails-credentials-staging='EDITOR="nvim" rails credentials:edit --environment staging'
alias ngrok-rt='~/./ngrok http 5000 --subdomain=remoteteam'
alias zp-update-gql='bin/rake graphql:prepare && yarn generate-client-types'
